image: cirrusci/flutter

stages:
  - testing

get_dependency:
  stage: testing
  script:
    - cd ./libraries/dependencies && flutter pub get
    - cd ./libraries/core && flutter pub get
    - cd ./features/home && flutter pub get
    - cd ./features/movie && flutter pub get
    - cd ./features/tv && flutter pub get
    - flutter pub get

unit_test:
  stage: testing
  script:
    - cd ./libraries/dependencies && flutter pub get
    - cd ./libraries/core && flutter pub get
    - cd ./features/home && flutter pub get
    - cd ./features/movie && flutter pub get
    - cd ./features/tv && flutter pub get
    - flutter pub get
    - ./test.sh
